movies/urls.py
from django.urls import path
from . import views

app_name = 'movies'
urlpatterns = [
    path('', views.index, name="index"),
    path('create/', views.create, name="create"),
    path('detail/<int:pk>/', views.detail, name="detail"),
    path('update/<int:pk>/', views.update, name="update"),
    path('<int:pk>/delete/', views.delete, name="delete"),
]

mypjt/urls.py
from django.contrib import admin
from django.urls import path, include
from movies import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('movies/', include("movies.urls")),
] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

movies/models.py
from django.db import models

# Create your models here.
class Movie(models.Model):
    title = models.CharField(max_length=200)
    storyline = models.TextField()
    image = models.ImageField(blank=True)

movies/forms.py
from django import forms
from .models import Movie

class MovieForm(forms.ModelForm):  # ModelForm 상속
    class Meta:  # Meta 클래스에 작성할거야
        model = Movie  # 대상 모델을 등록
        fields = '__all__'  # 모델의 필드 중 뭘 활용할건지

movies/views.py
from django.shortcuts import render, redirect
from .models import Movie
from .forms import MovieForm



# Create your views here.
def index(request):
    movies = Movie.objects.all()
    context = {
        'movies': movies
    }
    return render(request, 'movies/index.html', context)


def create(request):
    if request.method == 'POST':
        form = MovieForm(request.POST, request.FILES)
        if form.is_valid():
            movie = form.save()
            return redirect('movies:detail', movie.pk)
    else:
        form = MovieForm()
    context = {
        'form': form,
    }
    return render(request, 'movies/create.html', context)


def detail(request, pk):
    movie = Movie.objects.get(pk=pk)
    context = {
        'movie': movie
    }
    return render(request, 'movies/detail.html', context)


def update(request, pk):
    movie = Movie.objects.get(pk=pk)
    if request.method == 'POST':
        form = MovieForm(request.POST, request.FILES, instance=movie)
        if form.is_valid():
            form.save()
            return redirect('movies:detail', movie.pk)
    else:   
        form = MovieForm(instance=movie)
    context = {
    'movie': movie,
    'form': form,
    }
    return render(request, 'movies/update.html', context)

def delete(request, pk):
    movie = Movie.objects.get(pk=pk)
    movie.delete()
    return redirect('movies:index')

movies/templates/movies/create.html
{% extends "base.html" %}

{% block title %}영화 등록 페이지{% endblock title %}

{% block content %}
<form action="{% url 'movies:create' %}" method="POST" enctype="multipart/form-data">
  {% csrf_token %}
  {{ form.as_p }}
  <button type="submit" class="btn btn-primary">SUBMIT</button>
</form>
{% endblock content %}

movies/templates/movies/detail.html
{% extends "base.html" %}

{% block title %}영화 상세 페이지{% endblock title %}

{% block content %}
  <div class="container mt-4">
    {% if movie.image %}
      <img src="{{ movie.image.url }}" alt="{{ movie.title }}" class="img-fluid mb-3" style="max-width: 300px; max-height: 400px;"> <!-- 이미지 크기 조정 -->
    {% else %}
      <p>이미지가 없습니다.</p>
    {% endif %}
    
    <h2>{{ movie.title }}</h2>
    <h5>{{ movie.storyline }}</h5>
    <hr class="my-4">
    
    <div class="d-flex justify-content-start mt-4"> <!-- 왼쪽 정렬 -->
      <a href="{% url 'movies:update' movie.pk %}" class="btn btn-warning me-2">UPDATE</a>
      <a href="{% url 'movies:delete' movie.pk %}" class="btn btn-danger">DELETE</a>
    </div>
    
    <hr class="my-4">
    <a href="/movies/" class="btn btn-primary">HOME</a>
  </div>
{% endblock content %}

movies/templates/movies/index.html
{% extends "base.html" %}

{% block title %}메인 페이지{% endblock title %}

{% block content %}
  <a href="{% url 'movies:create' %}" class="btn btn-success mt-3 mb-3">NEW</a>

  <div class="row">
    {% for movie in movies %}
      <div class="col-md-4 mb-4"> <!-- 3개의 카드가 한 줄에 배치됨 -->
        <div class="card mx-2" style="height: 350px;"> <!-- 카드의 높이를 고정 및 좌우 여백 추가 -->
          <h4 class="card-header">{{ movie.title }}</h4>
          <div class="card-body d-flex flex-column" style="overflow: hidden;"> <!-- 내용이 넘칠 경우 숨김 -->
            <p class="card-text flex-grow-1" style="overflow: hidden;">{{ movie.storyline }}</p>
            <a href="{% url 'movies:detail' movie.pk %}" class="btn btn-primary mt-auto">Detail</a> <!-- 버튼을 카드 하단에 고정 -->
          </div>
        </div>
      </div>
    {% endfor %}
  </div>
{% endblock content %}

movies/templates/movies/update.html
{% extends "base.html" %}

{% block title %}영화 수정 페이지{% endblock title %}

{% block content %}
<form action="{% url 'movies:update' movie.pk %}" method="POST" enctype="multipart/form-data">
  {% csrf_token %}
  {{ form.as_p }}
  <button type="submit" class="btn btn-primary">SUBMIT</button>
</form>
{% endblock content %}

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
  <title>Document</title>
</head>
<body>
  <h1>
    {% block title %}{% endblock title %}
  </h1>
  <div>
    {% block content %}{% endblock content %}
  </div>

</body>
</html>